sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 020428
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tA8HvvZhvehWCvBJ5sZ
    access-key-secret: iUiLRxgCEWiVDJlDXYlnKgydnVTuce
    bucket-name: web-xinzhao
  redis:
    host: localhost
    port: 6379
    password: 020428
    database: 10
  wechat:
    appid: wx11af1942b1f9e457
    secret: b4d69deab49e016cb3f5615150c3fe8b
    #TODO 微信支付无法使用
    #商户号
    mchid:
    #证书序列号
    mchSerialNO:
    #私钥文件
    privateKeyFilePath:
    #解密秘钥
    apiV3Key:
    #平台证书
    weChatPayCertFilePath:
    #回调地址，支付成功，微信发起，商户系统接受
    notifyUrl:
    #支付失败，微信发起
    refundNotifyUrl: